name: Terraform CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  terraform-validation:
    runs-on: ubuntu-latest
    name: Terraform Validation
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
        
    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true
      
    - name: Terraform Init
      id: init
      run: terraform init -backend=false
      
    - name: Terraform Validate
      id: validate
      run: terraform validate
      
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: latest
        
    - name: Run TFLint
      id: tflint
      run: |
        tflint --init
        tflint --format compact
        
    - name: Setup Python for Checkov
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Checkov
      run: pip install checkov
      
    - name: Run Checkov Security Scan
      run: checkov -f main.tf --framework terraform --quiet
      continue-on-error: true
      
    - name: Results Summary
      if: always()
      run: |
        echo "## Terraform Validation Results" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.fmt.outcome }}" == "success" ]; then
          echo "- Terraform Format: PASSED" >> $GITHUB_STEP_SUMMARY
        else
          echo "- Terraform Format: FAILED" >> $GITHUB_STEP_SUMMARY
        fi
        echo "- Terraform Init: SUCCESS" >> $GITHUB_STEP_SUMMARY
        echo "- Terraform Validate: SUCCESS" >> $GITHUB_STEP_SUMMARY
        echo "- TFLint: SUCCESS" >> $GITHUB_STEP_SUMMARY
        echo "- Security Scan: COMPLETED" >> $GITHUB_STEP_SUMMARY
        
    - name: Format Check Failed
      if: steps.fmt.outcome == 'failure'
      run: |
        echo "Terraform formatting check failed!"
        echo "Run 'terraform fmt -recursive' to fix formatting issues."
        exit 1
